spring.application.name: webapi

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wildangels
    username: root
    password: password
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect