spring.application.name: webapi

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dreadfall
    username: root
    password: password
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
security:
  secret: m8BhRrJz7NxCxHyyp14XKPwuvk89apIW8IN9w1rGTkDgRwE9HtRnWkWPv8kVklGT
  allowed.origins: "*"

logging:
  level:
    root: INFO
    com:
      dreadfallguild:
        webapi: TRACE