CREATE TABLE users
(
    USER_ID int NOT NULL AUTO_INCREMENT,
    USERNAME varchar(50) NOT NULL,
    PASSWORD varchar(50) NOT NULL,
    EMAIL varchar(30) NOT NULL,
    ROLE varchar(10) NOT NULL,
    CONSTRAINT USERS_PK PRIMARY KEY (USER_ID),
    CONSTRAINT UNIQUE UC_USERS (USERNAME, EMAIL)
);