CREATE TABLE users
(
    USER_ID INT NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(30) NOT NULL,
    ROLE VARCHAR(10) NOT NULL,
    CONSTRAINT USERS_PK PRIMARY KEY (USER_ID),
    CONSTRAINT UNIQUE UC_USERS (USERNAME, EMAIL)
);