CREATE TABLE shout_message
(
    MESSAGE_ID int NOT NULL AUTO_INCREMENT,
    USERNAME varchar(50) NOT NULL,
    MESSAGE varchar(255) NOT NULL,
    DATE_CREATED TIMESTAMP NOT NULL,
    CONSTRAINT SHOUT_MESSAGE_PK PRIMARY KEY (MESSAGE_ID)
);