CREATE TABLE news (
    NEWS_ID int NOT NULL AUTO_INCREMENT,
    TITLE varchar(255) NOT NULL,
    CONTENT varchar(4096) NOT NULL,
    VOTES int DEFAULT 0,
    CREATED_BY varchar(50) NOT NULL,
    DATE_CREATED TIMESTAMP NOT NULL,
    CONSTRAINT NEWS_PK PRIMARY KEY (NEWS_ID)
);