CREATE TABLE news (
    NEWS_ID INT NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(255) NOT NULL,
    CONTENT LONGTEXT NOT NULL,
    VOTES INT DEFAULT 0,
    CREATED_BY VARCHAR(50) NOT NULL,
    DATE_CREATED TIMESTAMP NOT NULL,
    CONSTRAINT NEWS_PK PRIMARY KEY (NEWS_ID)
);