CREATE TABLE news_comments (
    COMMENT_ID INT NOT NULL AUTO_INCREMENT,
    NEWS_ID INT NOT NULL,
    PARENT_ID INT,
    CONTENT LONGTEXT NOT NULL,
    CREATED_BY VARCHAR(50) NOT NULL,
    DATE_CREATED TIMESTAMP NOT NULL,
    CONSTRAINT COMMENT_PK PRIMARY KEY (COMMENT_ID)
);

CREATE INDEX IDX_COMMENTS_NEWS_ID ON news_comments(NEWS_ID);

INSERT INTO news_comments (NEWS_ID,PARENT_ID,CONTENT,CREATED_BY,DATE_CREATED) VALUES
	 (1,NULL,'I am a base comment','admin','2023-01-22 06:59:00'),
	 (1,1,'I am a reply','user','2023-01-22 07:00:00'),
	 (1,2,'I am a nested reply','user2','2023-01-22 07:03:00');